theme: minima
title: "H.P Lovecraft's site"
author: DanCrespo
email: danielcrespo@cresalex.com
description: >This site was made to set some books, information or any thing about the greatest and 
darkest writter H.P Lovecraft, the horror cosmic and black prose father. If someone wish to contribute 
with this site, adding content or deploying your code, let me say that you are welcome. Just contact me.

facebook_username: "Dan Cresalex"
github_username:  Nyarlatotep 

show_excerpts: true # set to false to remove excerpts on the homepage
